# type: ignore
"""content

Revision ID: aeb9fe314556
Revises: d0118d8ec0b4
Create Date: 2021-02-14 19:56:59.175268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aeb9fe314556"
down_revision = "d0118d8ec0b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.add_column(sa.Column("linked", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.drop_column("linked")

    # ### end Alembic commands ###
