# type: ignore
"""content

Revision ID: e0c73f066547
Revises: 2e4f8364f7e2
Create Date: 2021-06-20 12:42:31.056065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0c73f066547"
down_revision = "2e4f8364f7e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.add_column(sa.Column("api_type", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.drop_column("api_type")

    # ### end Alembic commands ###
