# type: ignore
"""content

Revision ID: ebc3f4bb0782
Revises: 29f675c35eee
Create Date: 2021-02-14 19:56:54.040372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ebc3f4bb0782"
down_revision = "29f675c35eee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.add_column(sa.Column("linked", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.drop_column("linked")

    # ### end Alembic commands ###
