# type: ignore
"""content

Revision ID: 6b1b10eb67de
Revises: 5b4bea08c27f
Create Date: 2021-02-14 19:56:56.267261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b1b10eb67de"
down_revision = "5b4bea08c27f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.add_column(sa.Column("linked", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.drop_column("linked")

    # ### end Alembic commands ###
