# type: ignore
"""content

Revision ID: 990fc1108317
Revises: a918b6b05d2f
Create Date: 2021-06-20 12:42:34.173918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "990fc1108317"
down_revision = "a918b6b05d2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.add_column(sa.Column("api_type", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medias", schema=None) as batch_op:
        batch_op.drop_column("api_type")

    # ### end Alembic commands ###
